# Generated by Django 3.1.7 on 2021-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_product_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_product_group',
            fields=[
                ('product_group_key', models.AutoField(primary_key=True, serialize=False)),
                ('product_group', models.CharField(max_length=100)),
                ('product_group_description', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100, null=True)),
                ('oe', models.CharField(max_length=100, null=True)),
                ('row_is_current', models.CharField(max_length=100)),
                ('row_start_date', models.DateTimeField()),
                ('row_end_date', models.DateTimeField()),
                ('row_change_reason', models.CharField(max_length=100)),
                ('import_version', models.CharField(max_length=100)),
                ('import_batch', models.CharField(max_length=100)),
                ('import_user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jcwf_dim_product_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage_product_group',
            fields=[
                ('product_group', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_group_description', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100, null=True)),
                ('oe', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jcwf_stage_product_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tran_product_group',
            fields=[
                ('product_group', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_group_description', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=100, null=True)),
                ('oe', models.CharField(max_length=100, null=True)),
                ('row_is_current', models.CharField(max_length=100)),
                ('row_start_date', models.DateTimeField()),
                ('row_end_date', models.DateTimeField()),
                ('row_change_reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jcwf_tran_product_group',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='dimProduct',
        ),
        migrations.DeleteModel(
            name='stageProduct',
        ),
        migrations.DeleteModel(
            name='tranProduct',
        ),
    ]
