# Generated by Django 3.1.7 on 2021-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('personemail', models.EmailField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'teststageperson',
                'managed': False,
            },
        ),
    ]
