# Generated by Django 3.1.7 on 2021-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dimProduct',
            fields=[
                ('productkey', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('mindeposit', models.CharField(max_length=100, null=True)),
                ('phaseoutdate', models.CharField(max_length=100, null=True)),
                ('discdate', models.CharField(max_length=100, null=True)),
                ('discontinued', models.CharField(max_length=100, null=True)),
                ('col', models.CharField(max_length=100)),
                ('rowiscurrent', models.CharField(max_length=100)),
                ('rowstartdate', models.DateTimeField()),
                ('rowenddate', models.DateTimeField()),
                ('rowchangereason', models.CharField(max_length=100)),
                ('importversion', models.CharField(max_length=100)),
                ('importbatch', models.CharField(max_length=100)),
                ('importuser', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dimproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='stageProduct',
            fields=[
                ('productid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('mindeposit', models.CharField(max_length=100, null=True)),
                ('phaseoutdate', models.CharField(max_length=100, null=True)),
                ('discdate', models.DateTimeField(max_length=100, null=True)),
                ('col', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stageproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tranProduct',
            fields=[
                ('productid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('producttype', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('mindeposit', models.CharField(max_length=100, null=True)),
                ('phaseoutdate', models.CharField(max_length=100, null=True)),
                ('discdate', models.DateTimeField(max_length=100, null=True)),
                ('discontinued', models.CharField(max_length=100)),
                ('col', models.CharField(max_length=100)),
                ('rowiscurrent', models.CharField(max_length=100)),
                ('rowstartdate', models.DateTimeField()),
                ('rowenddate', models.DateTimeField()),
                ('rowchangereason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tranproduct',
                'managed': False,
            },
        ),
    ]
