# Generated by Django 3.1.7 on 2021-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_product',
            fields=[
                ('product_key', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('min_deposit', models.CharField(max_length=100, null=True)),
                ('phase_out_date', models.CharField(max_length=100, null=True)),
                ('disc_date', models.CharField(max_length=100, null=True)),
                ('discontinued', models.CharField(max_length=100, null=True)),
                ('col', models.CharField(max_length=100)),
                ('row_is_current', models.CharField(max_length=100)),
                ('row_start_date', models.DateTimeField()),
                ('row_end_date', models.DateTimeField()),
                ('row_change_reason', models.CharField(max_length=100)),
                ('import_version', models.CharField(max_length=100)),
                ('import_batch', models.CharField(max_length=100)),
                ('import_user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dim_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage_product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('min_deposit', models.CharField(max_length=100, null=True)),
                ('phase_out_date', models.CharField(max_length=100, null=True)),
                ('disc_date', models.DateTimeField(max_length=100, null=True)),
                ('col', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'stage_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tran_product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('pdg', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('min_deposit', models.CharField(max_length=100, null=True)),
                ('phase_out_date', models.CharField(max_length=100, null=True)),
                ('disc_date', models.DateTimeField(max_length=100, null=True)),
                ('discontinued', models.CharField(max_length=100)),
                ('col', models.CharField(max_length=100)),
                ('row_is_current', models.CharField(max_length=100)),
                ('row_start_date', models.DateTimeField()),
                ('row_end_date', models.DateTimeField()),
                ('row_change_reason', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tran_product',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='dimProduct',
        ),
        migrations.DeleteModel(
            name='stageProduct',
        ),
        migrations.DeleteModel(
            name='tranProduct',
        ),
    ]
