# Generated by Django 3.1.7 on 2021-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempcolor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('colordescription', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tempcolor',
                'managed': False,
            },
        ),
    ]
