# Generated by Django 3.1.7 on 2021-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_date', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_date',
            fields=[
                ('date_date_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_date_name', models.DateTimeField()),
                ('date_full_date_usa', models.CharField(max_length=100)),
                ('date_day_of_week', models.CharField(max_length=100, null=True)),
                ('date_day_name', models.CharField(max_length=100)),
                ('date_day_of_month', models.CharField(max_length=100, null=True)),
                ('date_day_of_year', models.CharField(max_length=100, null=True)),
                ('date_week_of_year', models.CharField(max_length=100, null=True)),
                ('date_month_name', models.CharField(max_length=100, null=True)),
                ('date_month_of_year', models.CharField(max_length=100, null=True)),
                ('date_quarter', models.CharField(max_length=100, null=True)),
                ('date_quarter_name', models.CharField(max_length=100, null=True)),
                ('date_year_name', models.CharField(max_length=100, null=True)),
                ('date_is_weekday', models.CharField(max_length=100, null=True)),
                ('row_is_current', models.CharField(max_length=100)),
                ('row_start_date', models.DateTimeField()),
                ('row_end_date', models.DateTimeField()),
                ('row_change_reason', models.CharField(max_length=100)),
                ('import_version', models.CharField(max_length=100)),
                ('import_batch', models.CharField(max_length=100)),
                ('import_user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jcwf_dim_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage_date',
            fields=[
                ('date_date_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_date_name', models.DateTimeField()),
                ('date_full_date_usa', models.CharField(max_length=100)),
                ('date_day_of_week', models.CharField(max_length=100, null=True)),
                ('date_day_name', models.CharField(max_length=100)),
                ('date_day_of_month', models.CharField(max_length=100, null=True)),
                ('date_day_of_year', models.CharField(max_length=100, null=True)),
                ('date_week_of_year', models.CharField(max_length=100, null=True)),
                ('date_month_name', models.CharField(max_length=100, null=True)),
                ('date_month_of_year', models.CharField(max_length=100, null=True)),
                ('date_quarter', models.CharField(max_length=100, null=True)),
                ('date_quarter_name', models.CharField(max_length=100, null=True)),
                ('date_year_name', models.CharField(max_length=100, null=True)),
                ('date_is_weekday', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jcwf_stage_date',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='dimProduct',
        ),
        migrations.DeleteModel(
            name='stageProduct',
        ),
        migrations.DeleteModel(
            name='tranProduct',
        ),
    ]
