# Generated by Django 3.1.7 on 2021-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dimTable',
            fields=[
                ('tableid', models.AutoField(primary_key=True, serialize=False)),
                ('tablename', models.CharField(max_length=100)),
                ('lastbatchimported', models.CharField(max_length=100)),
                ('numberofrecordsimported', models.CharField(max_length=100)),
                ('lastimportversion', models.CharField(max_length=100)),
                ('lastimportuser', models.CharField(max_length=100)),
                ('rowiscurrent', models.CharField(max_length=100, null=True)),
                ('rowstartdate', models.CharField(max_length=100, null=True)),
                ('rowenddate', models.CharField(max_length=100, null=True)),
                ('rowchangereason', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'dimtable',
                'managed': False,
            },
        ),
    ]
