# Generated by Django 3.1.7 on 2021-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dim_table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('last_batch_imported', models.CharField(max_length=100)),
                ('number_of_records_imported', models.CharField(max_length=100)),
                ('last_import_version', models.CharField(max_length=100)),
                ('last_import_user', models.CharField(max_length=100)),
                ('row_is_current', models.CharField(max_length=100, null=True)),
                ('row_start_date', models.CharField(max_length=100, null=True)),
                ('row_end_date', models.CharField(max_length=100, null=True)),
                ('row_change_reason', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='dimTable',
        ),
    ]
