from django.db import models

# model types for reference
# models.CharField(max_length=100, null=False, primary_key=True)
# models.CharField(max_length=100, null=False)
# models.CharField(max_length=100)
# models.FloatField(max_digits=16, decimal_places=4)
# models.DateTimeField()
# models.ForeignKey(__name__, on_delete=models.CASCADE)
# models.TextField(max_length =500)

# models.ManyToManyField("self")
# models.OneToOneField()

# models.DateField() # I don't use often 
# models.IntegerField()
# models.AutoField() # An IntegerField that automatically increments according to available IDs.
# models.BinaryField() 
# models.BooleanField()
# models.DecimalField(max_digits=16, decimal_places=4)
# models.FloatField(max_digits=16, decimal_places=4)
# models.ImageField(max_digits=16, decimal_places=4)
# models.JSONField(max_digits=16, decimal_places=4)

# Create your models here.

class Stage_customer(models.Model):    
    customer_account = models.CharField(max_length=100, null=False, primary_key=True)
    customer_business_person = models.CharField(max_length=100, null=True)
    customer_name = models.CharField(max_length=100)
    customer_primary_phone = models.CharField(max_length=100, null=True)
    customer_zip = models.CharField(max_length=100, null=False)
    customer_street_1 = models.CharField(max_length=100, null=True)
    # customer_street_2 = models.CharField(max_length=100, null=True)
    # customer_street_3 = models.CharField(max_length=100, null=True)
    # customer_street_4 = models.CharField(max_length=100, null=True)
    customer_city = models.CharField(max_length=100, null=True)
    customer_state = models.CharField(max_length=100, null=True)
    customer_country = models.CharField(max_length=100, null=True)
    customer_address_type = models.CharField(max_length=100, null=True)
    customer_address_fax = models.CharField(max_length=100, null=True)
    # customer_country_code = models.CharField(max_length=100, null=True)
    # customer_idd_prefix = models.CharField(max_length=100, null=True)
    customer_account_activation_email = models.CharField(max_length=100, null=True)
    customer_advance_ship_notice = models.CharField(max_length=100, null=True)
    customer_order_submittal = models.CharField(max_length=100, null=True)
    customer_email_subscription = models.CharField(max_length=100, null=True)
    # customer_website = models.CharField(max_length=100, null=True)
    # customer_customer_reference = models.CharField(max_length=100, null=True)
    customer_default_order_comments = models.CharField(max_length=100, null=True)
    customer_default_invoice_comments = models.CharField(max_length=100, null=True)
    # customer_hide_cost_on_order_confirmation = models.CharField(max_length=100, null=True)
    # customer_allow_duplicate_po = models.CharField(max_length=100, null=True)
    customer_first_name_last_name = models.CharField(max_length=100, null=True)
    customer_work_phone = models.CharField(max_length=100, null=True)
    customer_ext = models.CharField(max_length=100, null=True)
    customer_cell_phone = models.CharField(max_length=100, null=True)
    customer_home_phone = models.CharField(max_length=100, null=True)
    customer_fax = models.CharField(max_length=100, null=True)
    customer_corporate_account = models.CharField(max_length=100, null=True)
    customer_email_credit_hold = models.CharField(max_length=100, null=True)
    customer_credit_hold_email = models.CharField(max_length=100, null=True)
    customer_art_hold_email = models.CharField(max_length=100, null=True)
    customer_email_invoice = models.CharField(max_length=100, null=True)
    customer_invoice_notification = models.CharField(max_length=100, null=True)
    customer_email_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_email_statement = models.CharField(max_length=100, null=True)
    customer_statements = models.CharField(max_length=100, null=True)
    customer_email_credit_memo = models.CharField(max_length=100, null=True)
    customer_credit_memo_email = models.CharField(max_length=100, null=True)
    customer_email_return_reminder = models.CharField(max_length=100, null=True)
    customer_return_reminder_email = models.CharField(max_length=100, null=True)
    customer_reference_associate_email = models.CharField(max_length=100, null=True)
    customer_fed_tax_code = models.CharField(max_length=100, null=True)
    customer_fed_tax_freight = models.CharField(max_length=100, null=True)
    customer_fed_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_fed_certificate = models.CharField(max_length=100, null=True)
    customer_state_tax_code = models.CharField(max_length=100, null=True)
    customer_state_tax_freight = models.CharField(max_length=100, null=True)
    customer_state_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_state_certificate = models.CharField(max_length=100, null=True)
    customer_warehouse = models.CharField(max_length=100, null=True)
    customer_site = models.CharField(max_length=100, null=True)
    customer_type = models.CharField(max_length=100, null=True)
    customer_territory = models.CharField(max_length=100, null=True)
    customer_site_number = models.CharField(max_length=100, null=True)
    customer_source = models.CharField(max_length=100, null=True)
    # customer_royalty_included = models.CharField(max_length=100, null=True)
    customer_route_codes = models.CharField(max_length=100, null=True)
    customer_route_sequence = models.CharField(max_length=100, null=True)
    customer_ship_via = models.CharField(max_length=100, null=True)
    customer_price_suffix = models.CharField(max_length=100, null=True)
    customer_drop_ship = models.CharField(max_length=100, null=True)
    customer_high_low_discount = models.CharField(max_length=100, null=True)
    customer_bill_to_name = models.CharField(max_length=100, null=True)
    customer_bill_to_street_1 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_2 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_3 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_4 = models.CharField(max_length=100, null=True)
    customer_bill_to_city = models.CharField(max_length=100, null=True)
    customer_bill_to_state = models.CharField(max_length=100, null=True)
    customer_bill_to_zipcode = models.CharField(max_length=100, null=True)
    customer_bill_to_country = models.CharField(max_length=100, null=True)
    customer_bill_to_phone = models.CharField(max_length=100, null=True)
    customer_bill_to_fax = models.CharField(max_length=100, null=True)
    customer_opened = models.CharField(max_length=100, null=True)
    # customer_last_invoice = models.CharField(max_length=100, null=True)
    # customer_last_payment = models.CharField(max_length=100, null=True)
    customer_terms = models.CharField(max_length=100, null=True)
    customer_days = models.CharField(max_length=100, null=True)
    customer_other = models.CharField(max_length=100, null=True)
    customer_past_due_max = models.CharField(max_length=100, null=True)
    customer_invoice_due_days = models.CharField(max_length=100, null=True)
    customer_cod = models.CharField(max_length=100, null=True)
    customer_prepay_cc = models.CharField(max_length=100, null=True)
    customer_charge_freight = models.CharField(max_length=100, null=True)
    # customer_collector = models.CharField(max_length=100, null=True)
    customer_credit_hold_code = models.CharField(max_length=100, null=True)
    customer_credit_limit = models.CharField(max_length=100, null=True)
    customer_last_reviewed = models.CharField(max_length=100, null=True)
    customer_include_remakes = models.CharField(max_length=100, null=True)
    customer_on_any_order_lower = models.CharField(max_length=100, null=True)
    customer_on_any_order_higher = models.CharField(max_length=100, null=True)
    # customer_current_lower = models.CharField(max_length=100, null=True)
    # customer_current_higher = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_higher = models.CharField(max_length=100, null=True)
    customer_reference_1 = models.CharField(max_length=100, null=True)
    customer_waive_minimum_deposit = models.CharField(max_length=100, null=True)
    # customer_reference_2 = models.CharField(max_length=100, null=True)
    customer_account_suspended = models.CharField(max_length=100, null=True)
    customer_saleperson_1 = models.CharField(max_length=100, null=True)
    # customer_saleperson_2 = models.CharField(max_length=100, null=True)
    # customer_saleperson_3 = models.CharField(max_length=100, null=True)
    # customer_saleperson_4 = models.CharField(max_length=100, null=True)
    # customer_saleperson_5 = models.CharField(max_length=100, null=True)
    # customer_constant_1 = models.CharField(max_length=100, null=True)
    # customer_constant_2 = models.CharField(max_length=100, null=True)
    # customer_constant_3 = models.CharField(max_length=100, null=True)
    # customer_constant_4 = models.CharField(max_length=100, null=True)
    # customer_constant_5 = models.CharField(max_length=100, null=True)
    # customer_constant_6 = models.CharField(max_length=100, null=True)
    # customer_constant_7 = models.CharField(max_length=100, null=True)
    # customer_constant_8 = models.CharField(max_length=100, null=True)
    # customer_constant_9 = models.CharField(max_length=100, null=True)
    # customer_constant_10 = models.CharField(max_length=100, null=True)
    # customer_constant_11 = models.CharField(max_length=100, null=True)
    # customer_constant_12 = models.CharField(max_length=100, null=True)
    # customer_constant_13 = models.CharField(max_length=100, null=True)
    # customer_constant_14 = models.CharField(max_length=100, null=True)
    # customer_constant_15 = models.CharField(max_length=100, null=True)
    # customer_constant_16 = models.CharField(max_length=100, null=True)
    # customer_constant_17 = models.CharField(max_length=100, null=True)
    # customer_constant_18 = models.CharField(max_length=100, null=True)
    # customer_constant_19 = models.CharField(max_length=100, null=True)
    # customer_constant_20 = models.CharField(max_length=100, null=True)
    # user_defined_1 = models.CharField(max_length=100, null=True)
    # user_defined_2 = models.CharField(max_length=100, null=True)
    # user_defined_3 = models.CharField(max_length=100, null=True)
    # user_defined_4 = models.CharField(max_length=100, null=True)
    # user_defined_5 = models.CharField(max_length=100, null=True)
    # user_defined_6 = models.CharField(max_length=100, null=True)
    # user_defined_7 = models.CharField(max_length=100, null=True)
    # user_defined_8 = models.CharField(max_length=100, null=True)
    # user_defined_9 = models.CharField(max_length=100, null=True)
    # user_defined_10 = models.CharField(max_length=100, null=True)
    # user_defined_11 = models.CharField(max_length=100, null=True)
    # user_defined_12 = models.CharField(max_length=100, null=True)
    # user_defined_13 = models.CharField(max_length=100, null=True)
    # user_defined_14 = models.CharField(max_length=100, null=True)
    # user_defined_15 = models.CharField(max_length=100, null=True)
    # user_defined_16 = models.CharField(max_length=100, null=True)
    # user_defined_17 = models.CharField(max_length=100, null=True)
    # user_defined_18 = models.CharField(max_length=100, null=True)
    # user_defined_19 = models.CharField(max_length=100, null=True)
    # user_defined_20 = models.CharField(max_length=100, null=True)
    customer_customer_w_tax = models.CharField(max_length=100, null=True)
    customer_limit_number_of_dealer_logins_to = models.CharField(max_length=100, null=True)
    customer_days_to_hold_quotes = models.CharField(max_length=100, null=True)
    # customer_enable_price_calculation = models.CharField(max_length=100, null=True)
    # customer_enable_freight_calculation = models.CharField(max_length=100, null=True)
    # customer_collection_display = models.CharField(max_length=100, null=True)
    # customer_internal_xml_id = models.CharField(max_length=100, null=True)
    # customer_client_quote_letter_verbiage = models.CharField(max_length=100, null=True)
    # customer_booked_orders = models.CharField(max_length=100, null=True)
    # customer_deposits = models.CharField(max_length=100, null=True)
    # customer_balance_due = models.CharField(max_length=100, null=True)
    # customer_open_ar = models.CharField(max_length=100, null=True)
    # customer_30_day_ar = models.CharField(max_length=100, null=True)
    # customer_60_day_ar = models.CharField(max_length=100, null=True)
    # customer_90_day_ar = models.CharField(max_length=100, null=True)
    # customer_120_day_ar = models.CharField(max_length=100, null=True)
    # customer_unapplied = models.CharField(max_length=100, null=True)
    # customer_total_open_ar = models.CharField(max_length=100, null=True)
    # customer_ytd = models.CharField(max_length=100, null=True)
    # customer_previous_year = models.CharField(max_length=100, null=True)
    # customer_high_sale = models.CharField(max_length=100, null=True)
    # customer_py_high_sale = models.CharField(max_length=100, null=True)
    # customer_cogs = models.CharField(max_length=100, null=True)
    # customer_py_cogs = models.CharField(max_length=100, null=True)
    customer_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_pv_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_times_past_due = models.CharField(max_length=100, null=True)
    customer_py_times_past_due = models.CharField(max_length=100, null=True)

    class Meta:
        managed = False

        db_table = 'jcwf_stage_customer'

    def __str__(self):
      return self.customer_Account


class Tran_customer(models.Model):
    customer_account = models.CharField(max_length=100, null=False, primary_key=True)
    customer_business_person = models.CharField(max_length=100, null=True)
    customer_name = models.CharField(max_length=100)
    customer_primary_phone = models.CharField(max_length=100, null=True)
    customer_zip = models.CharField(max_length=100, null=False)
    customer_street_1 = models.CharField(max_length=100, null=True)
    # customer_street_2 = models.CharField(max_length=100, null=True)
    # customer_street_3 = models.CharField(max_length=100, null=True)
    # customer_street_4 = models.CharField(max_length=100, null=True)
    customer_city = models.CharField(max_length=100, null=True)
    customer_state = models.CharField(max_length=100, null=True)
    customer_country = models.CharField(max_length=100, null=True)
    customer_address_type = models.CharField(max_length=100, null=True)
    customer_address_fax = models.CharField(max_length=100, null=True)
    # customer_country_code = models.CharField(max_length=100, null=True)
    # customer_idd_prefix = models.CharField(max_length=100, null=True)
    customer_account_activation_email = models.CharField(max_length=100, null=True)
    customer_advance_ship_notice = models.CharField(max_length=100, null=True)
    customer_order_submittal = models.CharField(max_length=100, null=True)
    customer_email_subscription = models.CharField(max_length=100, null=True)
    # customer_website = models.CharField(max_length=100, null=True)
    # customer_customer_reference = models.CharField(max_length=100, null=True)
    customer_default_order_comments = models.CharField(max_length=100, null=True)
    customer_default_invoice_comments = models.CharField(max_length=100, null=True)
    # customer_hide_cost_on_order_confirmation = models.CharField(max_length=100, null=True)
    # customer_allow_duplicate_po = models.CharField(max_length=100, null=True)
    customer_first_name_last_name = models.CharField(max_length=100, null=True)
    customer_work_phone = models.CharField(max_length=100, null=True)
    customer_ext = models.CharField(max_length=100, null=True)
    customer_cell_phone = models.CharField(max_length=100, null=True)
    customer_home_phone = models.CharField(max_length=100, null=True)
    customer_fax = models.CharField(max_length=100, null=True)
    customer_corporate_account = models.CharField(max_length=100, null=True)
    customer_email_credit_hold = models.CharField(max_length=100, null=True)
    customer_credit_hold_email = models.CharField(max_length=100, null=True)
    customer_art_hold_email = models.CharField(max_length=100, null=True)
    customer_email_invoice = models.CharField(max_length=100, null=True)
    customer_invoice_notification = models.CharField(max_length=100, null=True)
    customer_email_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_email_statement = models.CharField(max_length=100, null=True)
    customer_statements = models.CharField(max_length=100, null=True)
    customer_email_credit_memo = models.CharField(max_length=100, null=True)
    customer_credit_memo_email = models.CharField(max_length=100, null=True)
    customer_email_return_reminder = models.CharField(max_length=100, null=True)
    customer_return_reminder_email = models.CharField(max_length=100, null=True)
    customer_reference_associate_email = models.CharField(max_length=100, null=True)
    customer_fed_tax_code = models.CharField(max_length=100, null=True)
    customer_fed_tax_freight = models.CharField(max_length=100, null=True)
    customer_fed_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_fed_certificate = models.CharField(max_length=100, null=True)
    customer_state_tax_code = models.CharField(max_length=100, null=True)
    customer_state_tax_freight = models.CharField(max_length=100, null=True)
    customer_state_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_state_certificate = models.CharField(max_length=100, null=True)
    customer_warehouse = models.CharField(max_length=100, null=True)
    customer_site = models.CharField(max_length=100, null=True)
    customer_type = models.CharField(max_length=100, null=True)
    customer_territory = models.CharField(max_length=100, null=True)
    customer_site_number = models.CharField(max_length=100, null=True)
    customer_source = models.CharField(max_length=100, null=True)
    # customer_royalty_included = models.CharField(max_length=100, null=True)
    customer_route_codes = models.CharField(max_length=100, null=True)
    customer_route_sequence = models.CharField(max_length=100, null=True)
    customer_ship_via = models.CharField(max_length=100, null=True)
    customer_price_suffix = models.CharField(max_length=100, null=True)
    customer_drop_ship = models.CharField(max_length=100, null=True)
    customer_high_low_discount = models.CharField(max_length=100, null=True)
    customer_bill_to_name = models.CharField(max_length=100, null=True)
    customer_bill_to_street_1 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_2 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_3 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_4 = models.CharField(max_length=100, null=True)
    customer_bill_to_city = models.CharField(max_length=100, null=True)
    customer_bill_to_state = models.CharField(max_length=100, null=True)
    customer_bill_to_zipcode = models.CharField(max_length=100, null=True)
    customer_bill_to_country = models.CharField(max_length=100, null=True)
    customer_bill_to_phone = models.CharField(max_length=100, null=True)
    customer_bill_to_fax = models.CharField(max_length=100, null=True)
    customer_opened = models.CharField(max_length=100, null=True)
    # customer_last_invoice = models.CharField(max_length=100, null=True)
    # customer_last_payment = models.CharField(max_length=100, null=True)
    customer_terms = models.CharField(max_length=100, null=True)
    customer_days = models.CharField(max_length=100, null=True)
    customer_other = models.CharField(max_length=100, null=True)
    customer_past_due_max = models.CharField(max_length=100, null=True)
    customer_invoice_due_days = models.CharField(max_length=100, null=True)
    customer_cod = models.CharField(max_length=100, null=True)
    customer_prepay_cc = models.CharField(max_length=100, null=True)
    customer_charge_freight = models.CharField(max_length=100, null=True)
    # customer_collector = models.CharField(max_length=100, null=True)
    customer_credit_hold_code = models.CharField(max_length=100, null=True)
    customer_credit_limit = models.CharField(max_length=100, null=True)
    customer_last_reviewed = models.CharField(max_length=100, null=True)
    customer_include_remakes = models.CharField(max_length=100, null=True)
    customer_on_any_order_lower = models.CharField(max_length=100, null=True)
    customer_on_any_order_higher = models.CharField(max_length=100, null=True)
    # customer_current_lower = models.CharField(max_length=100, null=True)
    # customer_current_higher = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_higher = models.CharField(max_length=100, null=True)
    customer_reference_1 = models.CharField(max_length=100, null=True)
    customer_waive_minimum_deposit = models.CharField(max_length=100, null=True)
    # customer_reference_2 = models.CharField(max_length=100, null=True)
    customer_account_suspended = models.CharField(max_length=100, null=True)
    customer_saleperson_1 = models.CharField(max_length=100, null=True)
    # customer_saleperson_2 = models.CharField(max_length=100, null=True)
    # customer_saleperson_3 = models.CharField(max_length=100, null=True)
    # customer_saleperson_4 = models.CharField(max_length=100, null=True)
    # customer_saleperson_5 = models.CharField(max_length=100, null=True)
    # customer_constant_1 = models.CharField(max_length=100, null=True)
    # customer_constant_2 = models.CharField(max_length=100, null=True)
    # customer_constant_3 = models.CharField(max_length=100, null=True)
    # customer_constant_4 = models.CharField(max_length=100, null=True)
    # customer_constant_5 = models.CharField(max_length=100, null=True)
    # customer_constant_6 = models.CharField(max_length=100, null=True)
    # customer_constant_7 = models.CharField(max_length=100, null=True)
    # customer_constant_8 = models.CharField(max_length=100, null=True)
    # customer_constant_9 = models.CharField(max_length=100, null=True)
    # customer_constant_10 = models.CharField(max_length=100, null=True)
    # customer_constant_11 = models.CharField(max_length=100, null=True)
    # customer_constant_12 = models.CharField(max_length=100, null=True)
    # customer_constant_13 = models.CharField(max_length=100, null=True)
    # customer_constant_14 = models.CharField(max_length=100, null=True)
    # customer_constant_15 = models.CharField(max_length=100, null=True)
    # customer_constant_16 = models.CharField(max_length=100, null=True)
    # customer_constant_17 = models.CharField(max_length=100, null=True)
    # customer_constant_18 = models.CharField(max_length=100, null=True)
    # customer_constant_19 = models.CharField(max_length=100, null=True)
    # customer_constant_20 = models.CharField(max_length=100, null=True)
    # user_defined_1 = models.CharField(max_length=100, null=True)
    # user_defined_2 = models.CharField(max_length=100, null=True)
    # user_defined_3 = models.CharField(max_length=100, null=True)
    # user_defined_4 = models.CharField(max_length=100, null=True)
    # user_defined_5 = models.CharField(max_length=100, null=True)
    # user_defined_6 = models.CharField(max_length=100, null=True)
    # user_defined_7 = models.CharField(max_length=100, null=True)
    # user_defined_8 = models.CharField(max_length=100, null=True)
    # user_defined_9 = models.CharField(max_length=100, null=True)
    # user_defined_10 = models.CharField(max_length=100, null=True)
    # user_defined_11 = models.CharField(max_length=100, null=True)
    # user_defined_12 = models.CharField(max_length=100, null=True)
    # user_defined_13 = models.CharField(max_length=100, null=True)
    # user_defined_14 = models.CharField(max_length=100, null=True)
    # user_defined_15 = models.CharField(max_length=100, null=True)
    # user_defined_16 = models.CharField(max_length=100, null=True)
    # user_defined_17 = models.CharField(max_length=100, null=True)
    # user_defined_18 = models.CharField(max_length=100, null=True)
    # user_defined_19 = models.CharField(max_length=100, null=True)
    # user_defined_20 = models.CharField(max_length=100, null=True)
    customer_customer_w_tax = models.CharField(max_length=100, null=True)
    customer_limit_number_of_dealer_logins_to = models.CharField(max_length=100, null=True)
    customer_days_to_hold_quotes = models.CharField(max_length=100, null=True)
    # customer_enable_price_calculation = models.CharField(max_length=100, null=True)
    # customer_enable_freight_calculation = models.CharField(max_length=100, null=True)
    # customer_collection_display = models.CharField(max_length=100, null=True)
    # customer_internal_xml_id = models.CharField(max_length=100, null=True)
    # customer_client_quote_letter_verbiage = models.CharField(max_length=100, null=True)
    # customer_booked_orders = models.CharField(max_length=100, null=True)
    # customer_deposits = models.CharField(max_length=100, null=True)
    # customer_balance_due = models.CharField(max_length=100, null=True)
    # customer_open_ar = models.CharField(max_length=100, null=True)
    # customer_30_day_ar = models.CharField(max_length=100, null=True)
    # customer_60_day_ar = models.CharField(max_length=100, null=True)
    # customer_90_day_ar = models.CharField(max_length=100, null=True)
    # customer_120_day_ar = models.CharField(max_length=100, null=True)
    # customer_unapplied = models.CharField(max_length=100, null=True)
    # customer_total_open_ar = models.CharField(max_length=100, null=True)
    # customer_ytd = models.CharField(max_length=100, null=True)
    # customer_previous_year = models.CharField(max_length=100, null=True)
    # customer_high_sale = models.CharField(max_length=100, null=True)
    # customer_py_high_sale = models.CharField(max_length=100, null=True)
    # customer_cogs = models.CharField(max_length=100, null=True)
    # customer_py_cogs = models.CharField(max_length=100, null=True)
    customer_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_pv_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_times_past_due = models.CharField(max_length=100, null=True)
    customer_py_times_past_due = models.CharField(max_length=100, null=True)

    row_is_current  = models.CharField(max_length=100, null=False)
    row_start_date  = models.DateTimeField()

    row_end_date  = models.DateTimeField()
    row_change_reason = models.CharField(max_length=100, null=False)

    class Meta:
        managed = False
        db_table = 'jcwf_tran_customer'

    def __str__(self):
        return self.customer_account


class Dim_customer(models.Model):
    customer_key = models.AutoField(primary_key=True)

    customer_account = models.CharField(max_length=100, null=False)
    customer_business_person = models.CharField(max_length=100, null=True)
    customer_name = models.CharField(max_length=100)
    customer_primary_phone = models.CharField(max_length=100, null=True)
    customer_zip = models.CharField(max_length=100, null=False)
    customer_street_1 = models.CharField(max_length=100, null=True)
    # customer_street_2 = models.CharField(max_length=100, null=True)
    # customer_street_3 = models.CharField(max_length=100, null=True)
    # customer_street_4 = models.CharField(max_length=100, null=True)
    customer_city = models.CharField(max_length=100, null=True)
    customer_state = models.CharField(max_length=100, null=True)
    customer_country = models.CharField(max_length=100, null=True)
    customer_address_type = models.CharField(max_length=100, null=True)
    customer_address_fax = models.CharField(max_length=100, null=True)
    # customer_country_code = models.CharField(max_length=100, null=True)
    # customer_idd_prefix = models.CharField(max_length=100, null=True)
    customer_account_activation_email = models.CharField(max_length=100, null=True)
    customer_advance_ship_notice = models.CharField(max_length=100, null=True)
    customer_order_submittal = models.CharField(max_length=100, null=True)
    customer_email_subscription = models.CharField(max_length=100, null=True)
    # customer_website = models.CharField(max_length=100, null=True)
    # customer_customer_reference = models.CharField(max_length=100, null=True)
    customer_default_order_comments = models.CharField(max_length=100, null=True)
    customer_default_invoice_comments = models.CharField(max_length=100, null=True)
    # customer_hide_cost_on_order_confirmation = models.CharField(max_length=100, null=True)
    # customer_allow_duplicate_po = models.CharField(max_length=100, null=True)
    customer_first_name_last_name = models.CharField(max_length=100, null=True)
    customer_work_phone = models.CharField(max_length=100, null=True)
    customer_ext = models.CharField(max_length=100, null=True)
    customer_cell_phone = models.CharField(max_length=100, null=True)
    customer_home_phone = models.CharField(max_length=100, null=True)
    customer_fax = models.CharField(max_length=100, null=True)
    customer_corporate_account = models.CharField(max_length=100, null=True)
    customer_email_credit_hold = models.CharField(max_length=100, null=True)
    customer_credit_hold_email = models.CharField(max_length=100, null=True)
    customer_art_hold_email = models.CharField(max_length=100, null=True)
    customer_email_invoice = models.CharField(max_length=100, null=True)
    customer_invoice_notification = models.CharField(max_length=100, null=True)
    customer_email_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_invoice_past_due_alert = models.CharField(max_length=100, null=True)
    customer_email_statement = models.CharField(max_length=100, null=True)
    customer_statements = models.CharField(max_length=100, null=True)
    customer_email_credit_memo = models.CharField(max_length=100, null=True)
    customer_credit_memo_email = models.CharField(max_length=100, null=True)
    customer_email_return_reminder = models.CharField(max_length=100, null=True)
    customer_return_reminder_email = models.CharField(max_length=100, null=True)
    customer_reference_associate_email = models.CharField(max_length=100, null=True)
    customer_fed_tax_code = models.CharField(max_length=100, null=True)
    customer_fed_tax_freight = models.CharField(max_length=100, null=True)
    customer_fed_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_fed_certificate = models.CharField(max_length=100, null=True)
    customer_state_tax_code = models.CharField(max_length=100, null=True)
    customer_state_tax_freight = models.CharField(max_length=100, null=True)
    customer_state_exempt_number = models.CharField(max_length=100, null=True)
    # customer_signed_state_certificate = models.CharField(max_length=100, null=True)
    customer_warehouse = models.CharField(max_length=100, null=True)
    customer_site = models.CharField(max_length=100, null=True)
    customer_type = models.CharField(max_length=100, null=True)
    customer_territory = models.CharField(max_length=100, null=True)
    customer_site_number = models.CharField(max_length=100, null=True)
    customer_source = models.CharField(max_length=100, null=True)
    # customer_royalty_included = models.CharField(max_length=100, null=True)
    customer_route_codes = models.CharField(max_length=100, null=True)
    customer_route_sequence = models.CharField(max_length=100, null=True)
    customer_ship_via = models.CharField(max_length=100, null=True)
    customer_price_suffix = models.CharField(max_length=100, null=True)
    customer_drop_ship = models.CharField(max_length=100, null=True)
    customer_high_low_discount = models.CharField(max_length=100, null=True)
    customer_bill_to_name = models.CharField(max_length=100, null=True)
    customer_bill_to_street_1 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_2 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_3 = models.CharField(max_length=100, null=True)
    # customer_bill_to_street_4 = models.CharField(max_length=100, null=True)
    customer_bill_to_city = models.CharField(max_length=100, null=True)
    customer_bill_to_state = models.CharField(max_length=100, null=True)
    customer_bill_to_zipcode = models.CharField(max_length=100, null=True)
    customer_bill_to_country = models.CharField(max_length=100, null=True)
    customer_bill_to_phone = models.CharField(max_length=100, null=True)
    customer_bill_to_fax = models.CharField(max_length=100, null=True)
    customer_opened = models.CharField(max_length=100, null=True)
    # customer_last_invoice = models.CharField(max_length=100, null=True)
    # customer_last_payment = models.CharField(max_length=100, null=True)
    customer_terms = models.CharField(max_length=100, null=True)
    customer_days = models.CharField(max_length=100, null=True)
    customer_other = models.CharField(max_length=100, null=True)
    customer_past_due_max = models.CharField(max_length=100, null=True)
    customer_invoice_due_days = models.CharField(max_length=100, null=True)
    customer_cod = models.CharField(max_length=100, null=True)
    customer_prepay_cc = models.CharField(max_length=100, null=True)
    customer_charge_freight = models.CharField(max_length=100, null=True)
    # customer_collector = models.CharField(max_length=100, null=True)
    customer_credit_hold_code = models.CharField(max_length=100, null=True)
    customer_credit_limit = models.CharField(max_length=100, null=True)
    customer_last_reviewed = models.CharField(max_length=100, null=True)
    customer_include_remakes = models.CharField(max_length=100, null=True)
    customer_on_any_order_lower = models.CharField(max_length=100, null=True)
    customer_on_any_order_higher = models.CharField(max_length=100, null=True)
    # customer_current_lower = models.CharField(max_length=100, null=True)
    # customer_current_higher = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_30_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_60_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_90_days_ar_higher = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_lower = models.CharField(max_length=100, null=True)
    # customer_120_days_ar_higher = models.CharField(max_length=100, null=True)
    customer_reference_1 = models.CharField(max_length=100, null=True)
    customer_waive_minimum_deposit = models.CharField(max_length=100, null=True)
    # customer_reference_2 = models.CharField(max_length=100, null=True)
    customer_account_suspended = models.CharField(max_length=100, null=True)
    customer_saleperson_1 = models.CharField(max_length=100, null=True)
    # customer_saleperson_2 = models.CharField(max_length=100, null=True)
    # customer_saleperson_3 = models.CharField(max_length=100, null=True)
    # customer_saleperson_4 = models.CharField(max_length=100, null=True)
    # customer_saleperson_5 = models.CharField(max_length=100, null=True)
    # customer_constant_1 = models.CharField(max_length=100, null=True)
    # customer_constant_2 = models.CharField(max_length=100, null=True)
    # customer_constant_3 = models.CharField(max_length=100, null=True)
    # customer_constant_4 = models.CharField(max_length=100, null=True)
    # customer_constant_5 = models.CharField(max_length=100, null=True)
    # customer_constant_6 = models.CharField(max_length=100, null=True)
    # customer_constant_7 = models.CharField(max_length=100, null=True)
    # customer_constant_8 = models.CharField(max_length=100, null=True)
    # customer_constant_9 = models.CharField(max_length=100, null=True)
    # customer_constant_10 = models.CharField(max_length=100, null=True)
    # customer_constant_11 = models.CharField(max_length=100, null=True)
    # customer_constant_12 = models.CharField(max_length=100, null=True)
    # customer_constant_13 = models.CharField(max_length=100, null=True)
    # customer_constant_14 = models.CharField(max_length=100, null=True)
    # customer_constant_15 = models.CharField(max_length=100, null=True)
    # customer_constant_16 = models.CharField(max_length=100, null=True)
    # customer_constant_17 = models.CharField(max_length=100, null=True)
    # customer_constant_18 = models.CharField(max_length=100, null=True)
    # customer_constant_19 = models.CharField(max_length=100, null=True)
    # customer_constant_20 = models.CharField(max_length=100, null=True)
    # user_defined_1 = models.CharField(max_length=100, null=True)
    # user_defined_2 = models.CharField(max_length=100, null=True)
    # user_defined_3 = models.CharField(max_length=100, null=True)
    # user_defined_4 = models.CharField(max_length=100, null=True)
    # user_defined_5 = models.CharField(max_length=100, null=True)
    # user_defined_6 = models.CharField(max_length=100, null=True)
    # user_defined_7 = models.CharField(max_length=100, null=True)
    # user_defined_8 = models.CharField(max_length=100, null=True)
    # user_defined_9 = models.CharField(max_length=100, null=True)
    # user_defined_10 = models.CharField(max_length=100, null=True)
    # user_defined_11 = models.CharField(max_length=100, null=True)
    # user_defined_12 = models.CharField(max_length=100, null=True)
    # user_defined_13 = models.CharField(max_length=100, null=True)
    # user_defined_14 = models.CharField(max_length=100, null=True)
    # user_defined_15 = models.CharField(max_length=100, null=True)
    # user_defined_16 = models.CharField(max_length=100, null=True)
    # user_defined_17 = models.CharField(max_length=100, null=True)
    # user_defined_18 = models.CharField(max_length=100, null=True)
    # user_defined_19 = models.CharField(max_length=100, null=True)
    # user_defined_20 = models.CharField(max_length=100, null=True)
    customer_customer_w_tax = models.CharField(max_length=100, null=True)
    customer_limit_number_of_dealer_logins_to = models.CharField(max_length=100, null=True)
    customer_days_to_hold_quotes = models.CharField(max_length=100, null=True)
    # customer_enable_price_calculation = models.CharField(max_length=100, null=True)
    # customer_enable_freight_calculation = models.CharField(max_length=100, null=True)
    # customer_collection_display = models.CharField(max_length=100, null=True)
    # customer_internal_xml_id = models.CharField(max_length=100, null=True)
    # customer_client_quote_letter_verbiage = models.CharField(max_length=100, null=True)
    # customer_booked_orders = models.CharField(max_length=100, null=True)
    # customer_deposits = models.CharField(max_length=100, null=True)
    # customer_balance_due = models.CharField(max_length=100, null=True)
    # customer_open_ar = models.CharField(max_length=100, null=True)
    # customer_30_day_ar = models.CharField(max_length=100, null=True)
    # customer_60_day_ar = models.CharField(max_length=100, null=True)
    # customer_90_day_ar = models.CharField(max_length=100, null=True)
    # customer_120_day_ar = models.CharField(max_length=100, null=True)
    # customer_unapplied = models.CharField(max_length=100, null=True)
    # customer_total_open_ar = models.CharField(max_length=100, null=True)
    # customer_ytd = models.CharField(max_length=100, null=True)
    # customer_previous_year = models.CharField(max_length=100, null=True)
    # customer_high_sale = models.CharField(max_length=100, null=True)
    # customer_py_high_sale = models.CharField(max_length=100, null=True)
    # customer_cogs = models.CharField(max_length=100, null=True)
    # customer_py_cogs = models.CharField(max_length=100, null=True)
    customer_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_pv_avg_days_to_pay = models.CharField(max_length=100, null=True)
    customer_times_past_due = models.CharField(max_length=100, null=True)
    customer_py_times_past_due = models.CharField(max_length=100, null=True)

    row_is_current  = models.CharField(max_length=100, null=False)
    row_start_date  = models.DateTimeField()
    row_end_date  = models.DateTimeField()
    row_change_reason = models.CharField(max_length=100, null=False)
    import_version = models.CharField(max_length=100, null=False)
    import_batch = models.CharField(max_length=100, null=False)
    import_user = models.CharField(max_length=100, null=False)

    class Meta:
        managed = False
        db_table = 'jcwf_dim_customer'

    def __str__(self):
        return self.customer_account
